modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="biomelighting"
version="1.0.0"
displayName="Biome Lighting"
logoFile="biomelighting.png"
credits="Thanks to Mysticpasta1 for figuring out the original code that was turned into BiomeLighting"
authors="Waterpicker, Mysticpasta1"
description="Library mod for adding per biome skylight"
[[dependencies.biomelighting]]
    modId="forge"
    mandatory=true
    versionRange="[47.+,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.biomelighting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.20.2)"
    ordering="NONE"
    side="BOTH"
